More debug for sigterm
It's actually the vpnc-script which is failing:

 + '[' connect = connect ']'
+ ip link set dev oc-6352-tun0 up mtu 1434
Error: Device for nexthop is not up.

Signed-off-by: David Woodhouse <dwmw2@infradead.org>